# Generated by Django 3.1.4 on 2021-01-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_car', '0003_auto_20210123_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentcar',
            name='rent_to',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
